services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: highload_architect
    ports:
      - "8080:8080"
    volumes:
      - ./build/libs:/app/build/libs
    environment:
      - POSTGRES_DB_URL=${POSTGRES_DB_URL}
      - POSTGRES_DB_USER=${POSTGRES_DB_USER}
      - POSTGRES_DB_PASSWORD=${POSTGRES_DB_PASSWORD}
      - LIQUIBASE_ENABLED=${LIQUIBASE_ENABLED}
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
