services:
  bms_db:
    image: postgres:latest
    container_name: highload_architect
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=highload_architect
      - POSTGRES_HOST=5432
    volumes:
      - ./docker_data/bms_db:/var/lib/postgresql/data
