spring:
  application:
    name: SocialNetwork
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_DB_USER}
    password: ${POSTGRES_DB_PASSWORD}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 10000
      pool-name: pg-pool
  liquibase:
    enabled: ${LIQUIBASE_ENABLED}
    change-log: classpath:db/changelog/db.changelog-master.xml

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: openapi.yml

auth:
  token:
    signing:
      key: 123456789123456789123456789123456789123456789123456789